using Kraken.Net.Enums;
using Kraken.Net.Objects.Internal;
using Kraken.Net.Objects.Models;
using Kraken.Net.Objects.Models.Futures;
using Kraken.Net.Objects.Models.Socket;
using Kraken.Net.Objects.Models.Socket.Futures;
using Kraken.Net.Objects.Sockets;
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Kraken.Net.Converters
{
    [JsonSerializable(typeof(KrakenSocketRequestV2<KrakenSocketSubRequest>))]
    [JsonSerializable(typeof(KrakenSocketResponseV2<KrakenSocketSubResponse>))]
    [JsonSerializable(typeof(KrakenSocketResponseV2<KrakenOrderResult[]>))]
    [JsonSerializable(typeof(KrakenSocketResponseV2<KrakenOrderResult>))]
    [JsonSerializable(typeof(KrakenSocketUpdateV2<KrakenTickerUpdate[]>))]
    [JsonSerializable(typeof(KrakenSocketUpdateV2<KrakenBalanceSnapshot[]>))]
    [JsonSerializable(typeof(KrakenSocketUpdateV2<KrakenBalanceUpdate[]>))]
    [JsonSerializable(typeof(KrakenSocketUpdateV2<KrakenOrderUpdate[]>))]
    [JsonSerializable(typeof(KrakenSocketUpdateV2<KrakenKlineUpdate[]>))]
    [JsonSerializable(typeof(KrakenSocketUpdateV2<KrakenTradeUpdate[]>))]
    [JsonSerializable(typeof(KrakenSocketUpdateV2<KrakenBookUpdate[]>))]
    [JsonSerializable(typeof(KrakenSocketUpdateV2<KrakenIndividualBookUpdate[]>))]
    [JsonSerializable(typeof(KrakenSocketUpdateV2<KrakenInstrumentUpdate>))]
    [JsonSerializable(typeof(OrderTypeMinimal))]
    [JsonSerializable(typeof(KrakenSocketResponseV2<KrakenSocketAmendOrderResult>))]
    [JsonSerializable(typeof(KrakenSocketResponseV2<KrakenSocketReplaceOrderResult>))]
    [JsonSerializable(typeof(KrakenSocketResponseV2<KrakenStreamCancelAllResult>))]
    [JsonSerializable(typeof(KrakenSocketResponseV2<KrakenCancelAfterResult>))]

    // End manual defined attributes

    [JsonSerializable(typeof(KrakenFeeScheduleVolumeResult))]
    [JsonSerializable(typeof(KrakenFuturesResult<Dictionary<string, decimal>>))]
    [JsonSerializable(typeof(KrakenFuturesResult<Dictionary<string, KrakenBalanceAvailable>>))]
    [JsonSerializable(typeof(KrakenFuturesResult<Dictionary<string, KrakenPosition>>))]
    [JsonSerializable(typeof(KrakenFuturesResult<Dictionary<string, KrakenLedgerEntry>>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenCursorPage<KrakenMovementStatus>>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenCursorPage<KrakenEarnStrategy>>))]
    [JsonSerializable(typeof(KrakenFuturesResult<Dictionary<string, KrakenAssetInfo>>))]
    [JsonSerializable(typeof(KrakenFuturesResult<Dictionary<string, KrakenSymbol>>))]
    [JsonSerializable(typeof(KrakenFuturesResult<Dictionary<string, KrakenRestTick>>))]
    [JsonSerializable(typeof(KrakenFuturesResult<Dictionary<string, KrakenOrderBook>>))]
    [JsonSerializable(typeof(KrakenFuturesResult<Dictionary<string, KrakenOrder>>))]
    [JsonSerializable(typeof(KrakenFuturesResult<Dictionary<string, KrakenUserTrade>>))]
    [JsonSerializable(typeof(KrakenFeeScheduleVolumeResult))]
    [JsonSerializable(typeof(KrakenResult<Dictionary<string, decimal>>))]
    [JsonSerializable(typeof(KrakenResult<Dictionary<string, KrakenBalanceAvailable>>))]
    [JsonSerializable(typeof(KrakenResult<Dictionary<string, KrakenPosition>>))]
    [JsonSerializable(typeof(KrakenResult<Dictionary<string, KrakenLedgerEntry>>))]
    [JsonSerializable(typeof(KrakenResult<KrakenCursorPage<KrakenMovementStatus>>))]
    [JsonSerializable(typeof(KrakenResult<KrakenCursorPage<KrakenEarnStrategy>>))]
    [JsonSerializable(typeof(KrakenResult<Dictionary<string, KrakenAssetInfo>>))]
    [JsonSerializable(typeof(KrakenResult<Dictionary<string, KrakenSymbol>>))]
    [JsonSerializable(typeof(KrakenResult<Dictionary<string, KrakenRestTick>>))]
    [JsonSerializable(typeof(KrakenResult<Dictionary<string, KrakenOrderBook>>))]
    [JsonSerializable(typeof(KrakenResult<Dictionary<string, KrakenOrder>>))]
    [JsonSerializable(typeof(KrakenResult<Dictionary<string, KrakenUserTrade>>))]
    [JsonSerializable(typeof(KrakenFuturesResult<Dictionary<string, decimal>>))]
    [JsonSerializable(typeof(KrakenFuturesPnlCurrencyResult))]
    [JsonSerializable(typeof(KrakenFundingRatesResult))]
    [JsonSerializable(typeof(KrakenFeeSchedulesResult))]
    [JsonSerializable(typeof(KrakenFuturesSymbolResult))]
    [JsonSerializable(typeof(KrakenFuturesSymbolStatusResult))]
    [JsonSerializable(typeof(KrakenFuturesTradeResult))]
    [JsonSerializable(typeof(KrakenFuturesTickersResult))]
    [JsonSerializable(typeof(KrakenFuturesUserTradeResult))]
    [JsonSerializable(typeof(KrakenFuturesPositionResult))]
    [JsonSerializable(typeof(KrakenFuturesLeverageResult))]
    [JsonSerializable(typeof(KrakenFuturesOpenOrderResult))]
    [JsonSerializable(typeof(KrakenFuturesOrderStatusResult))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenDepositMethod[]>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenDepositAddress[]>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenMovementStatus[]>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenWithdrawAddress[]>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenWithdrawMethod[]>))]
    [JsonSerializable(typeof(KrakenResult<KrakenDepositMethod[]>))]
    [JsonSerializable(typeof(KrakenResult<KrakenDepositAddress[]>))]
    [JsonSerializable(typeof(KrakenResult<KrakenMovementStatus[]>))]
    [JsonSerializable(typeof(KrakenResult<KrakenWithdrawAddress[]>))]
    [JsonSerializable(typeof(KrakenResult<KrakenWithdrawMethod[]>))]
    [JsonSerializable(typeof(KrakenSocketUpdateV2<KrakenStreamSystemStatus[]>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenFeeSchedule[]>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenFundingRate[]>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenFuturesLeverage[]>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenFuturesOpenOrder[]>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenFuturesOrderStatus[]>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenFuturesPnlCurrency[]>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenFuturesPosition[]>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenFuturesSymbol[]>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenFuturesSymbolStatus[]>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenFuturesTicker[]>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenFuturesUserTrade[]>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenFuturesStreamUserTrade[]>))]
    [JsonSerializable(typeof(KrakenBalancesResult))]
    [JsonSerializable(typeof(KrakenFuturesOrderBookResult))]
    [JsonSerializable(typeof(KrakenFuturesTickerResult))]
    [JsonSerializable(typeof(KrakenFuturesSelfTradeResult))]
    [JsonSerializable(typeof(KrakenFuturesOrderPlaceResult))]
    [JsonSerializable(typeof(KrakenFuturesOrderEditResult))]
    [JsonSerializable(typeof(KrakenFuturesOrderCancelResult))]
    [JsonSerializable(typeof(KrakenFuturesCancelledOrdersResult))]
    [JsonSerializable(typeof(KrakenFuturesCancelAfterResult))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenTradeBalance>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenLedgerPage>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenTradeVolume>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenWithdrawInfo>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenWithdraw>))]
    [JsonSerializable(typeof(KrakenFuturesResult<bool>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenReferenceId>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenWebSocketToken>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenAllocationsCursorPage>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenEarnStatus>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenServerTime>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenSystemStatus>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenKlinesResult>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenTradesResult>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenSpreadsResult>))]
    [JsonSerializable(typeof(KrakenFuturesResult<OpenOrdersPage>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenClosedOrdersPage>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenUserTradesPage>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenBatchOrderResult>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenPlacedOrder>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenEditOrder>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenCancelResult>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenCancelAfterResult>))]
    [JsonSerializable(typeof(KrakenResult<KrakenTradeBalance>))]
    [JsonSerializable(typeof(KrakenResult<KrakenLedgerPage>))]
    [JsonSerializable(typeof(KrakenResult<KrakenTradeVolume>))]
    [JsonSerializable(typeof(KrakenResult<KrakenWithdrawInfo>))]
    [JsonSerializable(typeof(KrakenResult<KrakenWithdraw>))]
    [JsonSerializable(typeof(KrakenResult<bool>))]
    [JsonSerializable(typeof(KrakenResult<KrakenReferenceId>))]
    [JsonSerializable(typeof(KrakenResult<KrakenWebSocketToken>))]
    [JsonSerializable(typeof(KrakenResult<KrakenAllocationsCursorPage>))]
    [JsonSerializable(typeof(KrakenResult<KrakenEarnStatus>))]
    [JsonSerializable(typeof(KrakenResult<KrakenServerTime>))]
    [JsonSerializable(typeof(KrakenResult<KrakenSystemStatus>))]
    [JsonSerializable(typeof(KrakenResult<KrakenKlinesResult>))]
    [JsonSerializable(typeof(KrakenResult<KrakenTradesResult>))]
    [JsonSerializable(typeof(KrakenResult<KrakenSpreadsResult>))]
    [JsonSerializable(typeof(KrakenResult<OpenOrdersPage>))]
    [JsonSerializable(typeof(KrakenResult<KrakenClosedOrdersPage>))]
    [JsonSerializable(typeof(KrakenResult<KrakenUserTradesPage>))]
    [JsonSerializable(typeof(KrakenResult<KrakenBatchOrderResult>))]
    [JsonSerializable(typeof(KrakenResult<KrakenPlacedOrder>))]
    [JsonSerializable(typeof(KrakenResult<KrakenEditOrder>))]
    [JsonSerializable(typeof(KrakenResult<KrakenCancelResult>))]
    [JsonSerializable(typeof(KrakenResult<KrakenCancelAfterResult>))]
    [JsonSerializable(typeof(HashSet<string>))]
    [JsonSerializable(typeof(KrakenSocketResponseV2<object>))]
    [JsonSerializable(typeof(KrakenSocketRequestV2<KrakenSocketPlaceOrderRequestV2>))]
    [JsonSerializable(typeof(KrakenSocketRequestV2<KrakenSocketPlaceMultipleOrderRequestV2>))]
    [JsonSerializable(typeof(KrakenSocketRequestV2<KrakenSocketEditOrderRequest>))]
    [JsonSerializable(typeof(KrakenSocketRequestV2<KrakenSocketReplaceOrderRequest>))]
    [JsonSerializable(typeof(KrakenSocketRequestV2<KrakenSocketCancelOrdersRequestV2>))]
    [JsonSerializable(typeof(KrakenSocketRequestV2<KrakenSocketAuthRequestV2>))]
    [JsonSerializable(typeof(KrakenSocketRequestV2<KrakenSocketCancelAfterRequest>))]
    [JsonSerializable(typeof(IDictionary<string, object>))]
    [JsonSerializable(typeof(KrakenCursorPage<KrakenAllocation>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenFuturesBalances>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenFuturesCancelAfter>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenFuturesCancelledOrders>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenFuturesOrderBook>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenFuturesOrderResult>))]
    [JsonSerializable(typeof(KrakenFuturesResult<SelfTradeStrategy>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenFuturesTicker>))]
    [JsonSerializable(typeof(KrakenFuturesResult<KrakenFuturesTrade>))]
    [JsonSerializable(typeof(KrakenFuturesTradeUpdate[]))]
    [JsonSerializable(typeof(KrakenKlineUpdate[]))]
    [JsonSerializable(typeof(KrakenTradeUpdate[]))]
    [JsonSerializable(typeof(KrakenBalanceSnapshot[]))]
    [JsonSerializable(typeof(KrakenOrderUpdate[]))]
    [JsonSerializable(typeof(KrakenInfoEvent[]))]
    [JsonSerializable(typeof(KrakenSocketPlaceOrderRequestV2Trigger[]))]
    [JsonSerializable(typeof(KrakenSocketPlaceOrderRequestV2Condition[]))]
    [JsonSerializable(typeof(KrakenAllocationsCursorPage[]))]
    [JsonSerializable(typeof(KrakenAllocation[]))]
    [JsonSerializable(typeof(KrakenAllocatedAmount[]))]
    [JsonSerializable(typeof(KrakenBondingAwarded[]))]
    [JsonSerializable(typeof(KrakenBondingAllocation[]))]
    [JsonSerializable(typeof(KrakenAllocationRewarded[]))]
    [JsonSerializable(typeof(KrakenAllocationPayout[]))]
    [JsonSerializable(typeof(KrakenAssetInfo[]))]
    [JsonSerializable(typeof(KrakenBalanceAvailable[]))]
    [JsonSerializable(typeof(KrakenCancelAfterResult[]))]
    [JsonSerializable(typeof(KrakenCancelResult[]))]
    [JsonSerializable(typeof(KrakenEarnStatus[]))]
    [JsonSerializable(typeof(KrakenEarnStrategy[]))]
    [JsonSerializable(typeof(LockTypeInfo[]))]
    [JsonSerializable(typeof(YieldSourceType[]))]
    [JsonSerializable(typeof(AutoCompoundType[]))]
    [JsonSerializable(typeof(AprEstimate[]))]
    [JsonSerializable(typeof(KrakenEditOrder[]))]
    [JsonSerializable(typeof(KrakenFeeEntry[]))]
    [JsonSerializable(typeof(KrakenKline[]))]
    [JsonSerializable(typeof(KrakenStreamKline[]))]
    [JsonSerializable(typeof(KrakenLedgerEntry[]))]
    [JsonSerializable(typeof(KrakenOrder[]))]
    [JsonSerializable(typeof(KrakenOrderInfo[]))]
    [JsonSerializable(typeof(KrakenStreamOrder[]))]
    [JsonSerializable(typeof(KrakenOrderBook[]))]
    [JsonSerializable(typeof(KrakenOrderBookEntry[]))]
    [JsonSerializable(typeof(KrakenStreamOrderBook[]))]
    [JsonSerializable(typeof(KrakenStreamOrderBookEntry[]))]
    [JsonSerializable(typeof(KrakenOrderRequest[]))]
    [JsonSerializable(typeof(KrakenPageData[]))]
    [JsonSerializable(typeof(OpenOrdersPage[]))]
    [JsonSerializable(typeof(KrakenClosedOrdersPage[]))]
    [JsonSerializable(typeof(KrakenUserTradesPage[]))]
    [JsonSerializable(typeof(KrakenLedgerPage[]))]
    [JsonSerializable(typeof(KrakenBatchOrderResult[]))]
    [JsonSerializable(typeof(KrakenPlacedBatchOrder[]))]
    [JsonSerializable(typeof(KrakenPlacedOrder[]))]
    [JsonSerializable(typeof(KrakenPlacedOrderDescription[]))]
    [JsonSerializable(typeof(KrakenPosition[]))]
    [JsonSerializable(typeof(KrakenReferenceId[]))]
    [JsonSerializable(typeof(KrakenServerTime[]))]
    [JsonSerializable(typeof(KrakenSpread[]))]
    [JsonSerializable(typeof(KrakenStreamSpread[]))]
    [JsonSerializable(typeof(KrakenSymbol[]))]
    [JsonSerializable(typeof(KrakenSystemStatus[]))]
    [JsonSerializable(typeof(KrakenTick[]))]
    [JsonSerializable(typeof(KrakenRestTick[]))]
    [JsonSerializable(typeof(KrakenStreamTick[]))]
    [JsonSerializable(typeof(KrakenTickInfo[]))]
    [JsonSerializable(typeof(KrakenLastTrade[]))]
    [JsonSerializable(typeof(KrakenBestEntry[]))]
    [JsonSerializable(typeof(KrakenTrade[]))]
    [JsonSerializable(typeof(KrakenTradeBalance[]))]
    [JsonSerializable(typeof(KrakenTradeVolume[]))]
    [JsonSerializable(typeof(KrakenFeeStruct[]))]
    [JsonSerializable(typeof(KrakenUserTrade[]))]
    [JsonSerializable(typeof(KrakenStreamUserTrade[]))]
    [JsonSerializable(typeof(KrakenWithdraw[]))]
    [JsonSerializable(typeof(KrakenWithdrawInfo[]))]
    [JsonSerializable(typeof(KrakenChallengeRequest[]))]
    [JsonSerializable(typeof(KrakenChallengeResponse[]))]
    [JsonSerializable(typeof(KrakenEvent[]))]
    [JsonSerializable(typeof(KrakenFuturesEvent[]))]
    [JsonSerializable(typeof(KrakenAccountLogResult[]))]
    [JsonSerializable(typeof(KrakenAccountLog[]))]
    [JsonSerializable(typeof(KrakenBalancesResult[]))]
    [JsonSerializable(typeof(KrakenBalances[]))]
    [JsonSerializable(typeof(KrakenFuturesBalances[]))]
    [JsonSerializable(typeof(KrakenCashBalances[]))]
    [JsonSerializable(typeof(KrakenFeeScheduleVolumeResult[]))]
    [JsonSerializable(typeof(KrakenFeeSchedulesResult[]))]
    [JsonSerializable(typeof(KrakenFee[]))]
    [JsonSerializable(typeof(KrakenFundingRatesResult[]))]
    [JsonSerializable(typeof(KrakenFuturesCachedOrder[]))]
    [JsonSerializable(typeof(KrakenFuturesCancelAfterResult[]))]
    [JsonSerializable(typeof(KrakenFuturesCancelAfter[]))]
    [JsonSerializable(typeof(KrakenFuturesCancelledOrdersResult[]))]
    [JsonSerializable(typeof(KrakenFuturesCancelledOrders[]))]
    [JsonSerializable(typeof(KrakenFuturesKlines[]))]
    [JsonSerializable(typeof(KrakenFuturesKline[]))]
    [JsonSerializable(typeof(KrakenFuturesLeverageResult[]))]
    [JsonSerializable(typeof(KrakenFuturesMarginRequirementsInternal[]))]
    [JsonSerializable(typeof(KrakenFuturesMarginRequirements[]))]
    [JsonSerializable(typeof(KrakenFuturesMaxOrderSizeInternal[]))]
    [JsonSerializable(typeof(KrakenFuturesMaxOrderSize[]))]
    [JsonSerializable(typeof(KrakenFuturesOpenOrderResult[]))]
    [JsonSerializable(typeof(KrakenFuturesOrder[]))]
    [JsonSerializable(typeof(KrakenFuturesOrderBookResult[]))]
    [JsonSerializable(typeof(KrakenFuturesOrderBook[]))]
    [JsonSerializable(typeof(KrakenFuturesOrderBookEntry[]))]
    [JsonSerializable(typeof(KrakenFuturesOrderId[]))]
    [JsonSerializable(typeof(KrakenFuturesOrderCancelResult[]))]
    [JsonSerializable(typeof(KrakenFuturesOrderPlaceResult[]))]
    [JsonSerializable(typeof(KrakenFuturesOrderEditResult[]))]
    [JsonSerializable(typeof(KrakenFuturesOrderResult[]))]
    [JsonSerializable(typeof(KrakenFuturesOrderEvent[]))]
    [JsonSerializable(typeof(KrakenFuturesOrderStatusResult[]))]
    [JsonSerializable(typeof(KrakenFuturesPlatfromNotificationInternalResult[]))]
    [JsonSerializable(typeof(KrakenFuturesPlatfromNotificationResult[]))]
    [JsonSerializable(typeof(KrakenFuturesPlatfromNotification[]))]
    [JsonSerializable(typeof(KrakenFuturesPnlCurrencyResult[]))]
    [JsonSerializable(typeof(KrakenFuturesPositionResult[]))]
    [JsonSerializable(typeof(KrakenFuturesResult[]))]
    [JsonSerializable(typeof(KrakenFuturesError[]))]
    [JsonSerializable(typeof(KrakenFuturesSelfTradeResult[]))]
    [JsonSerializable(typeof(KrakenFuturesSymbolResult[]))]
    [JsonSerializable(typeof(KrakenFutureMarginLevel[]))]
    [JsonSerializable(typeof(KrakenFuturesSymbolStatusResult[]))]
    [JsonSerializable(typeof(KrakenFuturesTickersResult[]))]
    [JsonSerializable(typeof(KrakenFuturesTickerResult[]))]
    [JsonSerializable(typeof(KrakenFuturesTradeResult[]))]
    [JsonSerializable(typeof(KrakenFuturesTrade[]))]
    [JsonSerializable(typeof(KrakenFuturesUserExecutionEvents[]))]
    [JsonSerializable(typeof(KrakenFuturesExecutionElement[]))]
    [JsonSerializable(typeof(KrakenFuturesExecutionEventWrapper[]))]
    [JsonSerializable(typeof(KrakenFuturesExecutionEvent[]))]
    [JsonSerializable(typeof(KrakenFuturesExecution[]))]
    [JsonSerializable(typeof(KrakenFuturesOrderData[]))]
    [JsonSerializable(typeof(KrakenFuturesExecutionOrder[]))]
    [JsonSerializable(typeof(KrakenFuturesUserTradeResult[]))]
    [JsonSerializable(typeof(KrakenMarginAccountBalances[]))]
    [JsonSerializable(typeof(KrakenMarginRequirements[]))]
    [JsonSerializable(typeof(KrakenAuxiliaryAccountInfo[]))]
    [JsonSerializable(typeof(KrakenMultiCollateralMarginBalances[]))]
    [JsonSerializable(typeof(KrakenFlexCurrencySummary[]))]
    [JsonSerializable(typeof(KrakenTriggerOptions[]))]
    [JsonSerializable(typeof(KrakenBalanceSnapshotWallet[]))]
    [JsonSerializable(typeof(KrakenBookUpdate[]))]
    [JsonSerializable(typeof(KrakenBookUpdateEntry[]))]
    [JsonSerializable(typeof(KrakenIndividualBookUpdate[]))]
    [JsonSerializable(typeof(KrakenIndividualBookUpdateEntry[]))]
    [JsonSerializable(typeof(KrakenOrderResult[]))]
    [JsonSerializable(typeof(KrakenOrderUpdateFee[]))]
    [JsonSerializable(typeof(KrakenSocketAmendOrderResult[]))]
    [JsonSerializable(typeof(KrakenSocketOrderRequest[]))]
    [JsonSerializable(typeof(KrakenSocketReplaceOrderResult[]))]
    [JsonSerializable(typeof(KrakenStreamCancelAllResult[]))]
    [JsonSerializable(typeof(KrakenTickerUpdate[]))]
    [JsonSerializable(typeof(KrakenWebSocketToken[]))]
    [JsonSerializable(typeof(KrakenBalanceUpdate[]))]
    [JsonSerializable(typeof(KrakenFuturesAccountLogsSnapshotUpdate[]))]
    [JsonSerializable(typeof(KrakenFuturesAccountLogsUpdate[]))]
    [JsonSerializable(typeof(KrakenFuturesBalancesUpdate[]))]
    [JsonSerializable(typeof(KrakenFlexFutures[]))]
    [JsonSerializable(typeof(KrakenFlexCrossBalance[]))]
    [JsonSerializable(typeof(KrakenFlexIsolatedBalance[]))]
    [JsonSerializable(typeof(KrakenFlexFuturesCurrency[]))]
    [JsonSerializable(typeof(KrakenFutureBalance[]))]
    [JsonSerializable(typeof(KrakenFuturesHeartbeatUpdate[]))]
    [JsonSerializable(typeof(KrakenFuturesMiniTickerUpdate[]))]
    [JsonSerializable(typeof(KrakenFuturesNotificationUpdate[]))]
    [JsonSerializable(typeof(KrakenFuturesNotifcation[]))]
    [JsonSerializable(typeof(KrakenFuturesOpenPositionUpdate[]))]
    [JsonSerializable(typeof(KrakenFuturesOpenPosition[]))]
    [JsonSerializable(typeof(KrakenFuturesBookSnapshotUpdate[]))]
    [JsonSerializable(typeof(KrakenFuturesBookUpdate[]))]
    [JsonSerializable(typeof(KrakenFuturesOpenOrdersSnapshotUpdate[]))]
    [JsonSerializable(typeof(KrakenFuturesOpenOrdersUpdate[]))]
    [JsonSerializable(typeof(KrakenFuturesSocketOpenOrder[]))]
    [JsonSerializable(typeof(KrakenFuturesTrailingStopOptions[]))]
    [JsonSerializable(typeof(KrakenFuturesSocketMessage[]))]
    [JsonSerializable(typeof(KrakenFuturesSubscribeMessage[]))]
    [JsonSerializable(typeof(KrakenFuturesSubscribeAuthMessage[]))]
    [JsonSerializable(typeof(KrakenFuturesUpdateMessage[]))]
    [JsonSerializable(typeof(KrakenFuturesTickerUpdate[]))]
    [JsonSerializable(typeof(KrakenFuturesTradesSnapshotUpdate[]))]
    [JsonSerializable(typeof(KrakenFuturesUserTradesUpdate[]))]
    [JsonSerializable(typeof(KrakenInstrumentUpdate[]))]
    [JsonSerializable(typeof(KrakenSymbolUpdateAsset[]))]
    [JsonSerializable(typeof(KrakenSymbolUpdateSymbol[]))]
    [JsonSerializable(typeof(KrakenResult))]
    [JsonSerializable(typeof(KrakenFuturesResponse))]
    [JsonSerializable(typeof(KrakenFuturesRequest))]
    [JsonSerializable(typeof(KrakenSocketRequestV2))]
    [JsonSerializable(typeof(KrakenSocketSubRequest))]
    [JsonSerializable(typeof(int?))]
    [JsonSerializable(typeof(int))]
    [JsonSerializable(typeof(long?))]
    [JsonSerializable(typeof(long))]
    [JsonSerializable(typeof(decimal?))]
    [JsonSerializable(typeof(decimal))]
    [JsonSerializable(typeof(DateTime))]
    [JsonSerializable(typeof(DateTime?))]
    internal partial class KrakenSourceGenerationContext : JsonSerializerContext
    {
    }
}
